---
name: "Scheduled Release"

concurrency:
  group: container-release
  cancel-in-progress: false

on:
  workflow_dispatch:
  schedule:
    # NOTE: The longest build for an app is ~1h30m
    - cron: "0 */6 * * *"

env:
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  determine-images:
    name: Determine Images to Build
    runs-on: ubuntu-latest
    outputs:
      imagesToBuild: ${{ steps.fetch.outputs.changes }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tools
        run: sudo apt-get install moreutils jo

      - name: Generate Token
        uses: actions/create-github-app-token@v1
        id: generate-token
        with:
          app-id: "${{ secrets.BOT_APP_ID }}"
          private-key: "${{ secrets.BOT_APP_PRIVATE_KEY }}"

      - name: Fetch new app versions
        id: fetch
        run: ./.github/scripts/fetch.sh
        env:
          TOKEN: "${{ steps.generate-token.outputs.token }}"

  images-build:
    uses: ./.github/workflows/action-image-build.yaml
    if: needs.determine-images.outputs.imagesToBuild != '[]'
    needs: ["determine-images"]
    with:
      imagesToBuild: "${{ needs.determine-images.outputs.imagesToBuild }}"
      pushImages: "true"
      sendNotification: "true"
    secrets: inherit
